modLoader="javafml"
loaderVersion="[40,)"
license="BSD-3-Clause"

[[mods]]
modId="xkdeco"
authors="XeKr, Snownee, TeaConMC"
version="${file.jarVersion}"
displayName="XeKr's Decoration"
description='''
Models and textures are created by XeKr: https://github.com/XeKr
'''

[[dependencies.xkdeco]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.xkdeco]]
modId="minecraft"
mandatory=true
versionRange="1.20.1"
ordering="NONE"
side="BOTH"

[[dependencies.xkdeco]]
modId="kiwi"
mandatory=true
versionRange="[11.5.5,11.7)"
ordering="NONE"
side="BOTH"